const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const policy=require('../utils/automationPolicy');
const routes=[{answer:'1',aliases:['starting a new business'],classification:'New Business',sequence_id:'11111111-1111-1111-1111-111111111111'},{answer:'2',aliases:['managing manually'],classification:'Manual Management',sequence_id:'22222222-2222-2222-2222-222222222222'}];
test('exact answers, configured aliases and ambiguous replies',()=>{
 assert.equal(policy.matchRoute(routes,'1').route.classification,'New Business');
 assert.equal(policy.matchRoute(routes,'10').review,true);
 assert.equal(policy.matchRoute(routes,'MANAGING manually!').route.classification,'Manual Management');
 assert.equal(policy.matchRoute(routes,'1 or 2').review,true);
 assert.equal(policy.matchRoute([...routes,{...routes[1],aliases:['starting a new business']}],'starting a new business').review,true);
});
test('template status, language and parameters must match; old name mapping is preserved',()=>{
 const template={name:'welcome',status:'APPROVED',language:'en_US',components:[{type:'BODY',text:'Hi {{1}}'}]};
 const step={approved_template_name:'welcome',template_language:'en_US',template_parameters:[{field:'name'}]};
 assert.equal(policy.templatePlan(step,[template],{name:'Asha'}).parameters[0].text,'Asha');
 assert.equal(policy.templatePlan({...step,template_parameters:[]},[template],{name:'Asha'}).message,'Hi Asha');
 assert.ok(policy.templatePlan(step,[{...template,status:'PENDING'}],{}).blocked);
 assert.ok(policy.templatePlan({...step,template_language:'en'},[template],{}).blocked);
 assert.ok(policy.templatePlan({...step,template_parameters:[{field:'email'}]},[template],{}).blocked);
 assert.ok(policy.templatePlan({...step,template_parameters:[{field:'name'},{field:'name'}]},[template],{}).blocked);
});
test('retry bounds and uncertain outcomes never imply a blind resend',()=>{
 assert.equal(policy.sendOutcome({success:false,transient:true,error:'rate limit'},1).status,'retry');
 assert.equal(policy.sendOutcome({success:false,transient:true,error:'rate limit'},4).status,'failed');
 assert.equal(policy.sendOutcome({success:false,uncertain:true},1).status,'uncertain');
 assert.equal(policy.sendOutcome({success:true},1).status,'uncertain');
 assert.equal(policy.sendOutcome({success:true,dev:true},1).status,'uncertain');
});
test('stop conditions distinguish manual pause from cancellation',()=>{
 assert.equal(policy.stopReason({ai_paused:true},{demo_booked:true}),null);
 assert.equal(policy.stopReason({opted_out:true},{}),'opted_out');
 assert.equal(policy.stopReason({has_demo:true},{demo_booked:true}),'demo_booked');
 assert.equal(policy.stopReason({is_won:true},{customer_converted:true}),'customer_converted');
 assert.equal(policy.stopReason({is_won:true},{}),null);
});
function moduleWithMocks(file,deps){const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{module,exports:module.exports,Date,console,require:name=>{if(name in deps)return deps[name];throw new Error('Unmocked dependency: '+name);}});return module.exports;}
const url=process.env.AUTOMATION_TEST_DATABASE_URL;
test('PostgreSQL migration, concurrent workers, routing and stop-condition integration',{skip:!url},async t=>{
 const parsed=new URL(url);
 assert.ok(['localhost','127.0.0.1'].includes(parsed.hostname)&&/^\/curvelead_test_/.test(parsed.pathname),'Only an explicitly selected local test database is permitted.');
 const {Pool,types}=require('pg');types.setTypeParser(1114,value=>new Date(value.replace(' ','T')+'Z'));const pool=new Pool({connectionString:url,max:12,options:'-c timezone=UTC'});
 const schema='automation_v5_'+Date.now();await pool.query(`CREATE SCHEMA ${schema}`);
 // Dedicated schema, never clear application tables.
 const db={query:async(sql,args)=>{const c=await pool.connect();try{await c.query(`SET search_path TO ${schema},public`);return await c.query(sql,args);}finally{c.release();}},transaction:async fn=>{const c=await pool.connect();try{await c.query('BEGIN');await c.query(`SET LOCAL search_path TO ${schema},public`);const result=await fn(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};
 t.after(async()=>{await pool.query(`DROP SCHEMA ${schema} CASCADE`);await pool.end();});
 await db.query(fs.readFileSync(path.join(__dirname,'fixtures/automationV5.sql'),'utf8'));
 const migration=fs.readFileSync(path.join(__dirname,'../models/migration_lead_automation_v5.sql'),'utf8');
 await db.query(migration);await db.query(migration); // Rerunnable, does not enrol anything.
 const policyDeps={'../config/db':db,'crypto':require('crypto'),'../services/whatsappService':{},'../utils/email':{},'../utils/templateVars':{substituteVars:(text,lead)=>text.replace(/\{\{name\}\}/g,lead.name)},'../services/groqService':{},'../utils/workspaceLocale':{localeFromSettings:()=>({timezone:'UTC'})},'../services/whatsappConsent':{decideConsent:({lead,category})=>category==='MARKETING'&&!lead.whatsapp_opt_in_at?{allowed:false,reason:'No opt-in'}:{allowed:true},templateCategory:template=>template?.category || 'MARKETING'},'../utils/automationPolicy':policy};
 const runner=moduleWithMocks('jobs/automationSequenceRunner.js',policyDeps);
 const routing=moduleWithMocks('services/automationReplies.js',{'../config/db':db,'../utils/automationPolicy':policy,'../jobs/automationSequenceRunner':runner});
 const recovery=moduleWithMocks('services/automationRecovery.js',{'../config/db':db,'../utils/automationPolicy':policy,'../jobs/automationSequenceRunner':runner,'./automationReplies':routing,'crypto':require('crypto')});
 const trigger=moduleWithMocks('utils/automationTriggers.js',{'../config/db':db,'../controllers/notificationController':{createNotification:async()=>{}},'./googleReviewRequest':{sendReviewRequest:async()=>{}}});
 const template={name:'welcome',language:'en_US',status:'APPROVED',category:'UTILITY',components:[{type:'BODY',text:'Hi {{1}}'}]};
 const reset=()=>db.query('TRUNCATE tenants CASCADE');
 async function seed({question=false,stops={},step={},lead={},legacy=false}={}){
  const settings={whatsapp_phone_number_id:'mock-phone',whatsapp_access_token:'mock-token',whatsapp_business_account_id:'mock-waba'};
  const tenant=(await db.query('INSERT INTO tenants(name,settings) VALUES($1,$2) RETURNING id',['test',JSON.stringify(settings)])).rows[0].id;
  const person=(await db.query('INSERT INTO leads(tenant_id,name,phone,source,product) VALUES($1,$2,$3,$4,$5) RETURNING id',[tenant,'Asha','123','website','Salonox'])).rows[0].id;
  for(const [key,value]of Object.entries(lead)){assert.ok(['ai_paused','opted_out','automation_unresponsive','won_at'].includes(key));await db.query(`UPDATE leads SET ${key}=$2 WHERE id=$1`,[person,value]);}
  const seq=(await db.query('INSERT INTO automation_sequences(tenant_id,name,stop_conditions) VALUES($1,$2,$3) RETURNING id',[tenant,'welcome',JSON.stringify(stops)])).rows[0].id;
  const branch=(await db.query('INSERT INTO automation_sequences(tenant_id,name) VALUES($1,$2) RETURNING id',[tenant,'branch'])).rows[0].id;
  await db.query('INSERT INTO automation_sequence_steps(tenant_id,sequence_id,step_order,message,delay_minutes) VALUES($1,$2,0,$3,0)',[tenant,branch,'branch message']);
  const replyRoutes=question?[{...routes[0],sequence_id:branch}]:[];
  const fields={channel:'whatsapp',message:'Hi {{name}}',delay_minutes:0,approved_template_name:legacy?null:'welcome',always_template:!legacy,template_language:'en_US',template_parameters:[{field:'name'}],reply_routes:replyRoutes,...step};
  await db.query(`INSERT INTO automation_sequence_steps(tenant_id,sequence_id,step_order,${Object.keys(fields).join(',')}) VALUES($1,$2,0,${Object.keys(fields).map((_,i)=>'$'+(i+3)).join(',')})`,[tenant,seq,...Object.values(fields).map(v=>Array.isArray(v)?JSON.stringify(v):v)]);
  await db.query(`INSERT INTO automation_sequence_steps(tenant_id,sequence_id,step_order,delay_minutes,message,approved_template_name) VALUES($1,$2,1,1440,'later','welcome')`,[tenant,seq]);
  const enrollment=(await db.query('INSERT INTO automation_enrollments(tenant_id,lead_id,sequence_id) VALUES($1,$2,$3) RETURNING id',[tenant,person,seq])).rows[0].id;
  return{tenant,person,seq,branch,enrollment};
 }
 let sends=0;const deps={db,listMessageTemplates:async()=>({success:true,templates:[template]}),sendTemplate:async()=>({success:true,wa_message_id:'mock-'+(++sends)}),sendTextMessage:async()=>({success:true,wa_message_id:'mock-'+(++sends)})};
 const state=async id=>(await db.query('SELECT * FROM automation_enrollments WHERE id=$1',[id])).rows[0];
 await t.test('concurrent workers send once and schedule after the previous step',async()=>{await reset();sends=0;const f=await seed();await Promise.all([runner.createRunner(deps)(),runner.createRunner(deps)()]);assert.equal(sends,1);const e=await state(f.enrollment);assert.equal(e.current_step,1);assert.equal(e.status,'active');assert.ok(new Date(e.next_send_at)-Date.now()>86000000);});
 await t.test('opt-out after fetch prevents sending',async()=>{await reset();sends=0;const f=await seed();await runner.createRunner({...deps,listMessageTemplates:async()=>{await db.query('UPDATE leads SET opted_out=true WHERE id=$1',[f.person]);return{success:true,templates:[template]};}})();assert.equal(sends,0);assert.equal((await state(f.enrollment)).status,'cancelled');});
 await t.test('manual cancellation and pause after fetch prevent sending',async()=>{for(const cancel of [true,false]){await reset();sends=0;const f=await seed();await runner.createRunner({...deps,listMessageTemplates:async()=>{await db.query(cancel?"UPDATE automation_enrollments SET status='cancelled' WHERE id=$1":'UPDATE leads SET ai_paused=true WHERE id=$1',[cancel?f.enrollment:f.person]);return{success:true,templates:[template]};}})();assert.equal(sends,0);assert.equal((await state(f.enrollment)).status,cancel?'cancelled':'active');if(!cancel){await db.query('UPDATE leads SET ai_paused=false WHERE id=$1',[f.person]);await runner.createRunner(deps)();assert.equal(sends,1);}}});
 await t.test('missing/unapproved templates block the same step',async()=>{for(const templates of [[],[{...template,status:'PENDING'}]]){await reset();sends=0;const f=await seed();await runner.createRunner({...deps,listMessageTemplates:async()=>({success:true,templates})})();assert.equal(sends,0);assert.equal((await state(f.enrollment)).status,'blocked');assert.equal((await state(f.enrollment)).current_step,0);}});
 await t.test('failed sends remain at the same step and transient retries stop at four',async()=>{await reset();const f=await seed();for(let i=0;i<4;i++){await runner.createRunner({...deps,sendTemplate:async()=>({success:false,transient:true,error:'rate limited'})})();assert.equal((await state(f.enrollment)).current_step,0);if(i<3)await db.query('UPDATE automation_enrollments SET next_send_at=now() WHERE id=$1',[f.enrollment]);}assert.equal((await state(f.enrollment)).status,'failed');});
 await t.test('uncertain outcomes and stale send intent never resend automatically',async()=>{await reset();sends=0;const f=await seed();await runner.createRunner({...deps,sendTemplate:async()=>{sends++;return{success:false,uncertain:true,error:'timeout'};}})();await runner.createRunner(deps)();assert.equal(sends,1);assert.equal((await state(f.enrollment)).status,'uncertain');await assert.rejects(recovery.createRecovery(db)({tenantId:f.tenant,enrollmentId:f.enrollment,action:'retry'}));await recovery.createRecovery(db)({tenantId:f.tenant,enrollmentId:f.enrollment,action:'confirmed_sent',providerId:'reconciled-id',note:'Verified against mock provider'});assert.equal((await state(f.enrollment)).current_step,1);});
 await t.test('durable sending marker recovers conservatively after a worker crash',async()=>{await reset();sends=0;const f=await seed();await db.query("INSERT INTO automation_send_attempts(tenant_id,enrollment_id,step_order,status) VALUES($1,$2,0,'sending')",[f.tenant,f.enrollment]);await runner.createRunner(deps)();assert.equal(sends,0);assert.equal((await state(f.enrollment)).status,'uncertain');});
 await t.test('duplicate replies atomically classify and start exactly one branch',async()=>{await reset();const f=await seed({question:true});await runner.createRunner(deps)();const input={tenantId:f.tenant,leadId:f.person,messageId:'reply-1',text:'1'};await Promise.all([routing.createReplyRouter(db)(input),routing.createReplyRouter(db)(input)]);assert.equal((await state(f.enrollment)).cancelled_reason,'reply_routed');assert.equal(Number((await db.query('SELECT count(*) FROM automation_enrollments WHERE sequence_id=$1',[f.branch])).rows[0].count),1);assert.deepEqual((await db.query('SELECT tags FROM leads WHERE id=$1',[f.person])).rows[0].tags,['New Business']);});
 await t.test('no question, ambiguous replies, tenant isolation and takeover',async()=>{await reset();let f=await seed({question:true});await routing.createReplyRouter(db)({tenantId:f.tenant,leadId:f.person,messageId:'early',text:'1'});assert.equal((await state(f.enrollment)).status,'active');await runner.createRunner(deps)();await routing.createReplyRouter(db)({tenantId:f.tenant,leadId:f.person,messageId:'ambiguous',text:'10'});assert.equal((await state(f.enrollment)).status,'human_review');assert.equal((await db.query('SELECT ai_paused FROM leads WHERE id=$1',[f.person])).rows[0].ai_paused,true);await reset();f=await seed({question:true});await runner.createRunner(deps)();await db.query('UPDATE leads SET ai_paused=true WHERE id=$1',[f.person]);await routing.createReplyRouter(db)({tenantId:f.tenant,leadId:f.person,messageId:'takeover',text:'1'});assert.equal((await state(f.enrollment)).status,'active');const other=(await db.query('INSERT INTO tenants(name) VALUES($1) RETURNING id',['other'])).rows[0].id;await routing.createReplyRouter(db)({tenantId:other,leadId:f.person,messageId:'wrong-tenant',text:'1'});assert.equal((await state(f.enrollment)).status,'active');});
 await t.test('booking and won events cancel only sequences configured to stop',async()=>{for(const kind of ['demo','won']){await reset();const f=await seed({stops:{demo_booked:kind==='demo',customer_converted:kind==='won'}});await runner.createRunner({...deps,listMessageTemplates:async()=>{if(kind==='demo')await db.query("INSERT INTO lead_followups(tenant_id,lead_id,followup_type) VALUES($1,$2,'demo')",[f.tenant,f.person]);else{await db.query("INSERT INTO lead_stages(tenant_id,name,is_won) VALUES($1,'Customer',true)",[f.tenant]);await db.query("UPDATE leads SET stage='Customer' WHERE id=$1",[f.person]);}return{success:true,templates:[template]};}})();assert.equal((await state(f.enrollment)).status,'cancelled');}await reset();const f=await seed();await db.query("INSERT INTO lead_followups(tenant_id,lead_id,followup_type) VALUES($1,$2,'demo')",[f.tenant,f.person]);assert.equal((await state(f.enrollment)).status,'active');});
 await t.test('legacy text/fallback and legacy reply cancellation are preserved',async()=>{await reset();sends=0;const f=await seed({legacy:true});await db.query("INSERT INTO whatsapp_messages(tenant_id,lead_id,direction,message) VALUES($1,$2,'inbound','hello')",[f.tenant,f.person]);await runner.createRunner(deps)();assert.equal(sends,1);await routing.createReplyRouter(db)({tenantId:f.tenant,leadId:f.person,messageId:'legacy-reply',text:'hello'});assert.equal((await state(f.enrollment)).cancelled_reason,'replied');});
 await t.test('reviewed routing requires explicit resume and classifies atomically',async()=>{await reset();const f=await seed({question:true});await runner.createRunner(deps)();await routing.createReplyRouter(db)({tenantId:f.tenant,leadId:f.person,messageId:'review-me',text:'10'});await assert.rejects(recovery.createRecovery(db)({tenantId:f.tenant,enrollmentId:f.enrollment,action:'route',answer:'1'}));await db.query('UPDATE leads SET ai_paused=false WHERE id=$1',[f.person]);await recovery.createRecovery(db)({tenantId:f.tenant,enrollmentId:f.enrollment,action:'route',answer:'1'});assert.equal((await state(f.enrollment)).cancelled_reason,'reply_routed');});
 await t.test('cross-tenant route targets are never enrolled',async()=>{await reset();const f=await seed({question:true});await runner.createRunner(deps)();const other=(await db.query("INSERT INTO tenants(name) VALUES('other') RETURNING id")).rows[0].id;const target=(await db.query("INSERT INTO automation_sequences(tenant_id,name) VALUES($1,'foreign') RETURNING id",[other])).rows[0].id;await db.query('UPDATE automation_enrollments SET awaiting_routes=$2 WHERE id=$1',[f.enrollment,JSON.stringify([{...routes[0],sequence_id:target}])]);await routing.createReplyRouter(db)({tenantId:f.tenant,leadId:f.person,messageId:'foreign-route',text:'1'});assert.equal((await state(f.enrollment)).status,'human_review');assert.equal(Number((await db.query('SELECT count(*) FROM automation_enrollments WHERE sequence_id=$1',[target])).rows[0].count),0);});
 await t.test('post-send transaction failure recovers without resending',async()=>{await reset();sends=0;const f=await seed();let calls=0;const crashDb={...db,transaction:fn=>db.transaction(async client=>{const result=await fn(client);if(++calls===2)throw new Error('Simulated commit failure');return result;})};await runner.createRunner({...deps,db:crashDb})();assert.equal(sends,1);await db.query("UPDATE automation_enrollments SET claim_until=now()-interval '1 minute' WHERE id=$1",[f.enrollment]);await runner.createRunner(deps)();assert.equal(sends,1);assert.equal((await state(f.enrollment)).status,'uncertain');});
 await t.test('a delayed webhook predating the question cannot route',async()=>{await reset();const f=await seed({question:true});await runner.createRunner(deps)();await routing.createReplyRouter(db)({tenantId:f.tenant,leadId:f.person,messageId:'old-message',text:'1',messageAt:new Date(Date.now()-600000)});assert.equal((await state(f.enrollment)).status,'active');assert.equal(Number((await db.query('SELECT count(*) FROM automation_enrollments WHERE sequence_id=$1',[f.branch])).rows[0].count),0);});
 await t.test('catalogue failures are bounded, and retries preserve manual pause',async()=>{await reset();const f=await seed();for(let i=0;i<4;i++){await runner.createRunner({...deps,listMessageTemplates:async()=>({success:false})})();if(i<3)await db.query('UPDATE automation_enrollments SET next_send_at=now() WHERE id=$1',[f.enrollment]);}assert.equal((await state(f.enrollment)).status,'failed');await db.query('UPDATE leads SET ai_paused=true WHERE id=$1',[f.person]);await recovery.createRecovery(db)({tenantId:f.tenant,enrollmentId:f.enrollment,action:'retry'});assert.equal((await state(f.enrollment)).status,'active');assert.equal((await db.query('SELECT ai_paused FROM leads WHERE id=$1',[f.person])).rows[0].ai_paused,true);});
 await t.test('controller saves draft configuration and validates route ownership',async()=>{await reset();const f=await seed();const controller=moduleWithMocks('controllers/automationController.js',{'../config/db':db,'../utils/automationPolicy':policy});let response;const res={status(code){this.code=code;return this;},json(body){response=body;}};const input={name:'draft enquiry',is_active:false,stop_conditions:{on_reply:true,demo_booked:true,customer_converted:true},steps:[{channel:'whatsapp',delay_minutes:0,message:'',always_template:true,approved_template_name:'welcome',template_language:'en_US',template_parameters:[{field:'name'}],reply_routes:[{...routes[0],sequence_id:f.branch}]}]};await controller.createSequence({tenantId:f.tenant,body:input},res);assert.ok(response.id);const draft=(await db.query('SELECT * FROM automation_sequences WHERE id=$1',[response.id])).rows[0];assert.equal(draft.is_active,false);assert.equal(draft.stop_conditions.demo_booked,true);const other=(await db.query("INSERT INTO tenants(name) VALUES('other') RETURNING id")).rows[0].id;await controller.createRule({tenantId:other,body:{name:'foreign',trigger_type:'new_lead',sequence_id:f.seq}},res);assert.equal(res.code,422);});
 await t.test('classification failure rolls back branch enrolment and webhook claim',async()=>{await reset();const f=await seed({question:true});await runner.createRunner(deps)();const brokenDb={transaction:fn=>db.transaction(client=>fn({query:async(sql,args)=>{if(sql.includes('UPDATE leads SET tags='))throw new Error('Simulated classification failure');return client.query(sql,args);}}))};const reply={tenantId:f.tenant,leadId:f.person,messageId:'atomic-reply',text:'1'};await assert.rejects(routing.createReplyRouter(brokenDb)(reply));assert.equal((await state(f.enrollment)).status,'active');assert.equal(Number((await db.query('SELECT count(*) FROM automation_enrollments WHERE sequence_id=$1',[f.branch])).rows[0].count),0);assert.equal(Number((await db.query('SELECT count(*) FROM automation_reply_events WHERE message_id=$1',['atomic-reply'])).rows[0].count),0);await routing.createReplyRouter(db)(reply);assert.equal((await state(f.enrollment)).cancelled_reason,'reply_routed');});
 await t.test('recorded opt-in resumes a consent-blocked step without advancing it',async()=>{await reset();const f=await seed();await runner.createRunner({...deps,listMessageTemplates:async()=>({success:true,templates:[{...template,category:'MARKETING'}]})})();assert.equal((await state(f.enrollment)).status,'blocked');assert.equal((await state(f.enrollment)).blocked_reason,'blocked_no_opt_in');const consent=moduleWithMocks('services/whatsappConsent.js',{'../config/db':db});await consent.recordOptIn({tenantId:f.tenant,leadId:f.person,source:'test'});await consent.resumeBlockedEnrollments({tenantId:f.tenant,leadIds:[f.person]});assert.equal((await state(f.enrollment)).status,'active');assert.equal((await state(f.enrollment)).current_step,0);});
 await t.test('product-specific triggers and once-only enrolment respect tenant ownership',async()=>{await reset();const f=await seed();await db.query('DELETE FROM automation_enrollments WHERE id=$1',[f.enrollment]);await db.query("INSERT INTO automation_rules(tenant_id,name,trigger_type,sequence_id,product_interest) VALUES($1,'product rule','new_lead',$2,'salonox')",[f.tenant,f.seq]);await trigger.checkNewLeadTriggers({tenantId:f.tenant,lead:{id:f.person,lead_score:'hot'}});assert.equal(Number((await db.query('SELECT count(*) FROM automation_enrollments WHERE lead_id=$1',[f.person])).rows[0].count),1);assert.equal(await trigger.enrollLead({tenantId:f.tenant,leadId:f.person,sequenceId:f.seq}),false);const other=(await db.query("INSERT INTO tenants(name) VALUES('other') RETURNING id")).rows[0].id;assert.equal(await trigger.enrollLead({tenantId:other,leadId:f.person,sequenceId:f.branch}),false);});
});
